# Generated by Django 5.1.3 on 2024-11-10 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checkup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("sequence_number", models.IntegerField()),
                ("description", models.TextField()),
                ("goals", models.TextField()),
                ("scheduled_for", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("phone", models.TextField()),
                ("plan_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("phone", models.TextField()),
                ("role", models.TextField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CheckupModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("module_type", models.TextField()),
                ("rationale", models.TextField()),
                ("sequence_order", models.IntegerField()),
                ("inputs", models.JSONField(default=dict)),
                ("outputs", models.JSONField(default=dict, null=True)),
                ("status", models.TextField(default="pending")),
                ("transcript", models.TextField(null=True)),
                (
                    "checkup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="checkups.checkup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="checkup",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="checkups.patient"
            ),
        ),
        migrations.CreateModel(
            name="PatientProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkups.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkups.provider",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="providers",
            field=models.ManyToManyField(
                through="checkups.PatientProvider", to="checkups.provider"
            ),
        ),
    ]
